{"name": "Проверка отображения ошибки при попытке сохранить обращение без заполненных данных", "status": "passed", "steps": [{"name": "Выделяется заявка номер: \"6\"", "status": "passed", "parameters": [{"name": "number", "value": "6"}], "start": 1579876289301, "stop": 1579876290071}, {"name": "Клик на кнопку \"Завершить назначение\"", "status": "passed", "start": 1579876290071, "stop": 1579876290312}, {"name": "Проверка отображения ошибки при завершении обращения", "status": "passed", "start": 1579876290312, "stop": 1579876290386}], "attachments": [{"name": "log", "source": "20e54ec9-03c5-4536-8060-e06e8852c6cf-attachment.txt", "type": "text/plain"}], "start": 1579876287614, "stop": 1579876290386, "uuid": "4c44230f-48c1-4817-bbf3-b36b595d7da6", "historyId": "98fd29f41e09050c3aea8c5126d36298", "testCaseId": "a31d7eba551ff8eb852ec8892552bb44", "fullName": "tests.test_do.TestUI#test_error_save_appointment_without_data", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_do"}, {"name": "subSuite", "value": "TestUI"}, {"name": "host", "value": "iMac-1.local"}, {"name": "thread", "value": "33282-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_do"}]}